### ISSUE TITLE
athm-simulator wrong url

### ISSUE THREAD

**Issue by ckristhoff** [evertec/athmovil-ios-sdk#2]
Greetings,

athm-simulator app has wrong url scheme.

Current schema: `athm-simulator`
Required: `athm`

**Comment by hansy-dev** [comment]
Hello

Could you tell me the version?  For the version 3.0 you should use the object ATHMPaymentSimulated instead of ATHMPaymentRequest. With ATHMPaymentSimulated object you should build the application Simulator, the simulator application is inside the folder Simulator.

Regards

**Comment by hansy-dev** [comment]
Hello

I close this issue because the target URL scheme depends on the ATHMPaymentSimulated or ATHMPaymentRequest. Version 3.0 is handling this URL scheme  selector.

Regards.
