### ISSUE TITLE
completed payment handler referenceNumber error on development

### ISSUE THREAD

**Issue by ckristhoff** [evertec/athmovil-ios-sdk#3]
Greetings
Completed payments in development mode are getting `nil` for `referenceNumber`.

You are using `transactionReference` instead of `referenceNumber`

https://github.com/evertec/athmovil-ios-sdk/blob/a0a23066c8d291d9d74a8dfa7b0eb7e93aa3732a/athmovil-checkout/Source/ATHMCheckout.swift#L223

**Comment by hansy-dev** [comment]
Hello

I recommend you that update to version 3.0.

Regards

**Comment by hansy-dev** [comment]
Hello

I close this issue because it is fixed in version 3.0

Regards
