### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by jmayapr** [evertec/athmovil-ios-sdk#6]
Is there any option in the future to incluide subscription just like Stripe or any other management software?

**Comment by hansy-dev** [comment]
Hello

No, at this moment it is only allowed by creating a business account and test the functionality with your business account. 

Regards

**Comment by Esorgre** [comment]
- [#Idx]

**Comment by Esorgre** [comment]
[[HICU]](C-1035)

**Comment by Esorgre** [comment]
> - [#Idx] 

@cristopherb-evertec
